### ISSUE TITLE
python model.py

### ISSUE THREAD

**Issue by linhanxiao** [openai/glow#23] opened 2018-07-23 07:32 UTC
when i run the model.py in the demo folder ,there is a error
tensorflow.python.framework.errors_impl.NotFoundError: /home/lhx/miniconda3/lib/python3.6/site-packages/blocksparse/blocksparse_ops.so: undefined symbol: _ZN10tensorflow7strings6StrCatERKNS0_8AlphaNumES3_S3_S3_

what is the reason?

**Comment by prafullasd** [comment] 2018-07-24 10:09
Duplicate of #28

**Closed by prafullasd** 2018-07-24 10:09 UTC
